# Generated by Django 4.0.2 on 2022-02-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receiita',
            new_name='Receita',
        ),
    ]
